services:
  db:
    image: postgres:18.1
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}" ]
      interval: 1s

  nginx:
    image: nginx:1.29.4-alpine
    ports:
      - "$APP_API_PROXY_PORT:80"
      - "4001:81"
    restart: unless-stopped
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  postgres_data:
  dashboard_dist: