services:
  db:
    image: postgres
    container_name: db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${APP_DB_USER} -d ${APP_DB_NAME}" ]
      interval: 1s

  shortie:
    image: krizzu/shortie:0.0.1-dev.02
    container_name: app
    restart: unless-stopped
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - db
    environment:
      APP_DB_URL: jdbc:postgresql://db:5432/${APP_DB_NAME}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_USER: ${APP_DB_USER}
      APP_ID_ALPHABET: ${APP_ID_ALPHABET}
      APP_AUTH_SECRET: ${APP_AUTH_SECRET}
      APP_ADMIN_PASSWORD: ${APP_ADMIN_PASSWORD}

volumes:
  postgres_data:
  dashboard_dist: